apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook2-ui
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: guestbook2-ui
  template:
    metadata:
      labels:
        app: guestbook2-ui
    spec:
      containers:
      - image: 485229547579.dkr.ecr.us-west-2.amazonaws.com/demo-ecr:1b5eca3a2ffb00438dd2ca66438b82ba7472660f
        name: guestbook2-ui
        ports:
        - containerPort: 8080
