apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook2-ui
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: guestbook2-ui
  template:
    metadata:
      labels:
        app: guestbook2-ui
    spec:
      containers:
      - image: 485229547579.dkr.ecr.us-west-2.amazonaws.com/demo-api:6c62aa703d31acb70db02b9b4690af70eaebb577
        name: guestbook2-ui
        ports:
        - containerPort: 8080
