apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../../../base/apps/guestbook2/
images:
- name: 485229547579.dkr.ecr.us-west-2.amazonaws.com/demo-api
  newTag: ec9106ddfe3cfd4d68a347d1eb7dd8a23d70cb82
