apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: organization-api
  template:
    metadata:
      labels:
        app: organization-api
    spec:
      containers:
      - image: 485229547579.dkr.ecr.us-west-2.amazonaws.com/demo-api:566e22cdc248b8da7a49fc8f6c7774bf1bbe5032
        name: organization-api
        ports:
        - containerPort: 10400
