
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-demo
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: project-demo
  template:
    metadata:
      labels:
        app: project-demo
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: project-demo
        ports:
        - containerPort: 80
