apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../../../base/apps/guestbook/
images:
- name: 485229547579.dkr.ecr.us-west-2.amazonaws.com/demo-ecr
  newTag: 698c2f9eee3027a659d0a78f5cbf2c2c30dd41a7
