apiVersion: v1	
kind: Service	
metadata:	
  name: guestbook-ui	
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  selector:
    app: guestbook-ui
  type: LoadBalancer
  ports:	
  - protocol: TCP
    port: 80
    targetPort: 8080
