apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/techvishal1988/dot-net-CD.git
    targetRevision: HEAD
    path: GitOps/ArgoCD/environments/dev/apps/guestbook2/
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
